restructuring, removed unneeded workflows (for now)
Signed-off-by: Peter Geurts <peter.geurts@proton.me>

diff --git a/.github/workflows/reusable-docker.yml b/.github/workflows/reusable-docker.yml
--- a/.github/workflows/reusable-docker.yml
+++ b/.github/workflows/reusable-docker.yml
@@ -10,9 +10,6 @@ on:
       container-image:
         type: string
         required: true
-      cache-tag:
-        type: string
-        required: true
 
 jobs:
   detect-changes:
@@ -29,9 +26,9 @@ jobs:
         id: set-matrix
         run: |
           # TODO switch this back before pushing
-          # CHANGES=$(git diff --name-only origin/${{ github.base_ref }}...HEAD)
+          # CHANGES=rcdt_nav2/
+          CHANGES=$(git diff --name-only origin/${{ github.base_ref }}...HEAD)
           # CHANGES=$(git diff --name-only origin/main...HEAD)
-          CHANGES=rcdt_nav2/
           
           COMPONENTS=$(yq -o=json '.components' components.yml | jq '[
             to_entries[] |
@@ -98,8 +95,8 @@ jobs:
           password: ${{ secrets.DOCKER_TOKEN }}
           # username: ${{ env.DOCKER_USERNAME }}
           # password: ${{ env.DOCKER_TOKEN }}
-      - name: Pull ${{ matrix.tag }}
-        run: docker pull rcdt/robotics:"${{ matrix.tag }}"-amd64 || echo "Image rcdt/robotics:${{ matrix.tag }}-amd64 not found on Docker Hub."
+      # - name: Pull ${{ matrix.tag }}
+      #   run: docker pull rcdt/robotics:"${{ matrix.tag }}"-amd64 || echo "Image rcdt/robotics:${{ matrix.tag }}-amd64 not found on Docker Hub."
       - name: Build and push ${{ matrix.tag }}
         uses: docker/build-push-action@v6
         with:
@@ -110,7 +107,11 @@ jobs:
           build-args: |
             BASE_IMAGE=${{ matrix.base_image }}-amd64
           cache-from: |
+            type=gha
             type=registry,ref=rcdt/robotics:${{ matrix.tag }}-amd64
-            type=registry,ref=rcdt/robotics:build-cache-latest
-          cache-to: type=registry,ref=rcdt/robotics:${{ matrix.tag }}-amd64,mode=max
+          cache-to: type=gha,mode=max
+          # cache-from: |
+          #   type=registry,ref=rcdt/robotics:cache-${{ matrix.tag }}-amd64
+          #   type=registry,ref=rcdt/robotics:cache-latest
+          # cache-to: type=registry,ref=rcdt/robotics:cache-${{ matrix.tag }}-amd64,mode=max
       - run: df -h /
